### ISSUE TITLE
Test Setup broken

### ISSUE THREAD

**Issue by Th33x1l3** [boakley/robotframework-pageobjectlibrary#5] opened 2016-07-04 10:11 UTC
When using your page object library, if you try to use the keyword 
`Test Setup   my_step`

(my_step is in this case a placeholder. It could be any keyword like for example   Open Test Browser, or Setup Config )

the my_step is never run. Suit Setup, Suit Teardown and Test Teardown runs ok. Only Test setup is not run.

**Comment by boakley** [comment] 2016-07-04 13:51
Can you please provide a test case? What you say sounds impossible - the page object library is just keywords, it doesn't affect how robot runs tests. 

What is "the keyword Test Setup"? And what is `my_step`?

**Comment by Th33x1l3** [comment] 2016-07-04 15:00
Test Setup is the basic keyword in robot framework --> http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-setup-and-teardown

my_step is just a example placeholder. You could put any keyword there. 

I'm running the testes on Ubuntu 16, using python 2.7, virtual environments. 
A test case for this problem is simple to do:

create a keyword `Open Test Browser`  
this keyword should open a firefox browser

Now in setup add the following

```
Test Setup    Open Test Browser
Suite Setup
Test Teardown    Close All Browsers
```

Now just add 2 tests. For example just open google and type anything on it.
The expected outcome is that for each test, robot opens a browser for the test, do something then close the browser. 

Now the behavior I'm observing is as follow: If i let Open Test Browser on `Test Setup` it's not run. But if i put it on `Suite Setup` it runs once (as expected). Just that it only runs for the 1st test.

**Comment by boakley** [comment] 2017-09-20 21:08
I am not able to duplicate this, and I can't think of how it is even possible for the page object library to cause a test setup to not work. When I did as you instructed, each test opened and then closed a new browser window as expected.

Sorry, but I'm going to have to close this since you didn't provide a complete test case I could use to duplicate the problem, and I can't duplicate it based on your description.

**Closed as completed by boakley** 2017-09-20 21:09 UTC

**Comment by iprentzas** [comment] 2021-04-28 08:48
I know this is a 4 year old thread, but I came upon this issue as well. Thing is that the reason this is happening is due to a conflict on the [Setup] tag, on the test cases level. If you try to have the "Test Setup" tag on the settings along with the [Setup] tag on the test case level, then a failure will occur

**Comment by boakley** [comment] 2021-04-28 14:36
This sounds like robot is working as designed. Are you saying this _only_ happens when using the page object library? Robot is designed for the `[Setup]` inside a test to override the `Test Setup` setting.

If the is happening only when using the page object library, please provide an example.
